"""English source templates and Simplified Chinese translations.

Keep entries explicit for review, duplicate detection and placeholder checks.
"""

ENTRIES = (
    ("Anime SDF Gen is already open in its editor window.", "Anime SDF Gen 已在编辑窗口中打开。"),
    ("Draft saved; original workspace restored.", "草稿已保存，原始工作区已恢复。"),
    ("Output channel", "输出通道"),
    (" · Fixed face plane", " · 固定面部平面"),
    (" · Snap", " · 吸附"),
    ("+  Add triangle", "+  添加三角形"),
    ("16-bit PNG", "16 位 PNG"),
    ("32-bit Float EXR", "32 位浮点 EXR"),
    ("8-bit PNG", "8 位 PNG"),
    (
        "360° orbit seam at {details}. Align the two sweeps’ endpoint artwork for a continuous orbit. Export is available.",
        "360° 旋转在{details}处存在接缝。请对齐两次扫掠的端点形状，使旋转连续。仍可导出。",
    ),
    ("Active: {name}", "活动对象：{name}"),
    (
        "Add and select a smooth three-point curve. Move/Rotate/Scale shortcuts adjust it; choose Lit area to carve light or Shadow area to darken.",
        "添加并选中一条平滑的三点闭合曲线。可用移动、旋转、缩放快捷键调整；选择“亮部”挖出亮区，或选择“暗部”添加阴影。",
    ),
    ("Add keyframe", "添加关键帧"),
    ("Add triangle", "添加三角形"),
    ("Adjust curves.", "调整曲线。"),
    (
        "An output filename points to a folder. Choose another file name.",
        "输出文件名指向了文件夹。请更换文件名。",
    ),
    ("An unexpected error occurred: {details}", "发生意外错误：{details}"),
    ("Anime SDF Gen Interaction", "Anime SDF Gen 交互"),
    ("Anime SDF Gen Settings", "Anime SDF Gen 设置"),
    ("Apply this curve earlier in the layer order.", "将此曲线移到更靠前的图层，优先应用。"),
    ("Apply this curve later in the layer order.", "将此曲线移到更靠后的图层，稍后应用。"),
    ("At least two keyframes per sweep are required.", "每次扫掠至少需要两个关键帧。"),
    ("Back", "背面"),
    ("Base name shared by the textures and editable project", "纹理和可编辑工程共用的基础文件名"),
    ("Cancel Generation", "取消生成"),
    ("Cancel generation", "取消生成"),
    ("Cannot place the {marker} marker on the selected face.", "无法在所选面部放置{marker}标记。"),
    (
        "Capture the active mesh selection or chosen vertex group, then orient and fit again",
        "读取活动网格的选中面或指定顶点组，然后重新定向和拟合",
    ),
    ("Center and fit the face in the views.", "在视图中居中显示面部，并调整为合适大小。"),
    ("Change orientation to choose a different UV map.", "返回定向步骤以更换 UV 贴图。"),
    ("Character left", "角色左侧"),
    ("Character right", "角色右侧"),
    ("Chin", "下巴"),
    (
        "Choose 8-bit PNG, 16-bit PNG (default), or 32-bit Float EXR for every output file.",
        "为所有输出文件选择 8 位 PNG、16 位 PNG（默认）或 32 位浮点 EXR。",
    ),
    (
        "Choose 8-bit PNG, 16-bit PNG, or 32-bit Float EXR.",
        "请选择 8 位 PNG、16 位 PNG 或 32 位浮点 EXR。",
    ),
    ("Choose Output Location", "选择输出位置"),
    (
        "Choose a file name without path separators or reserved characters.",
        "文件名不能包含路径分隔符或保留字符。",
    ),
    (
        "Choose a save location in Confirm before generating.",
        "请在“确认”步骤选择保存位置后再生成。",
    ),
    ("Choose a save location.", "请选择保存位置。"),
    ("Choose an RGB channel or an individual grayscale texture", "选择 RGB 通道或独立灰度纹理"),
    ("Choose an existing keyframe in a sweep row.", "请在扫掠行中选择一个已有关键帧。"),
    (
        "Choose an output channel or Separate for each texture map.",
        "请为每张纹理选择输出通道或“单独保存”。",
    ),
    ("Choose an output path before generation.", "生成前请先选择输出路径。"),
    (
        "Choose the destination and file name; files are written only by Generate & Finish",
        "选择目标位置和文件名；点击“生成并完成”后才会写入文件",
    ),
    (
        "Choose the destination folder and file name. Generate & Finish writes the files.",
        "选择目标文件夹和文件名。点击“生成并完成”后写入文件。",
    ),
    ("Choose the size of all exported textures.", "选择所有导出纹理的尺寸。"),
    ("Clean Face", "简洁面部"),
    (
        "Click on the visible face to place a marker. No surface was hit.",
        "请点击可见的面部表面来放置标记。本次点击未命中表面。",
    ),
    ("Close", "关闭"),
    (
        "Close this session and restore the workspace. Previously saved files are kept.",
        "关闭本次编辑并恢复原工作区。之前保存的文件会保留。",
    ),
    ("Commit verified output files", "写入已验证的输出文件"),
    ("Confirm.", "确认。"),
    ("Continue to Confirm before generating.", "请进入“确认”步骤后再生成。"),
    ("Contours", "轮廓"),
    ("Control", "控件"),
    ("Copy previous keyframe", "复制上一关键帧"),
    ("Copy the selected closed curve with a small offset.", "复制所选闭合曲线，并稍微偏移副本。"),
    ("Corner", "尖角"),
    ("Corner handles", "尖角控制柄"),
    ("Could not open editor: {details}", "无法打开编辑器：{details}"),
    ("Create", "创建"),
    (
        "Curve coordinates must be finite and within ±100 face units.",
        "曲线坐标必须为有限数，且在 ±100 个面部单位内。",
    ),
    ("Curve visibility", "曲线可见性"),
    (
        "Cut a lit area out of the shadow. This cutout also applies to earlier keyframes in the same sweep; edit its shape on this keyframe.",
        "从阴影中挖出亮部。该亮部也会应用到同次扫掠的更早关键帧；请在当前关键帧编辑其形状。",
    ),
    ("Default precision", "默认精度"),
    ("Delete", "删除"),
    ("Delete curve", "删除曲线"),
    ("Delete this point from the curve.", "从曲线中删除此点。"),
    ("Discard & Close", "放弃并关闭"),
    ("Discard & close", "放弃并关闭"),
    ("Dismiss warning", "隐藏警告"),
    ("Distance: columns", "距离变换：列"),
    ("Distance: rows", "距离变换：行"),
    ("Down", "下移"),
    (
        "Drag to smooth threshold values before UV baking. Can alter small details. 0 is Off; strength scales from a 2048-pixel face canvas. Escape cancels.",
        "拖动以平滑 UV 烘焙前的阈值，可能改变细节。0 表示关闭；强度以 2048 像素面部画布为基准缩放。按 Esc 取消。",
    ),
    ("Duplicate", "复制"),
    ("Duplicate curve", "复制曲线"),
    (
        "Each keyframe needs one main boundary followed by closed shapes.",
        "每个关键帧需要一条主边界，其后才能放置闭合形状。",
    ),
    (
        "Each packed RGB channel can contain only one texture map.",
        "每个 RGB 通道只能打包一张纹理。",
    ),
    ("Each sweep requires 2–33 keyframes.", "每次扫掠需要 2–33 个关键帧。"),
    ("Edit Existing SDF", "编辑已有 SDF"),
    ("Edit Shadow Shapes", "编辑阴影形状"),
    (
        "Edit the active point’s precise head-space coordinates and Bézier handle offsets. Use Move/Rotate/Scale shortcuts to transform selected points together.",
        "精确编辑活动点的头部空间坐标和贝塞尔控制柄偏移。可用移动、旋转、缩放快捷键同时调整所选点。",
    ),
    (
        "Edit the selected output, source, keyframe or point settings",
        "编辑所选输出、源模型、关键帧或控制点设置",
    ),
    (
        "Edit this frame of the complete boundary sweep. Selecting it pauses the light orbit.",
        "编辑完整边界扫掠中的此关键帧。选中后会暂停光照旋转。",
    ),
    ("Encode numerical precision", "编码数值精度"),
    ("Encode {filename}", "编码 {filename}"),
    (
        "Enter a precise amount. 0 is Off. Smoothing can alter small details; hard shadow edges remain hard.",
        "输入精确数值。0 表示关闭。平滑可能改变细节，但不会将硬阴影边缘变软。",
    ),
    (
        "Existing files in this output set will be replaced together after verification.",
        "验证完成后，将一起替换此组输出中已有的文件。",
    ),
    (
        "Expand this view. Ctrl+Space also toggles focus.",
        "放大此视图。Ctrl+Space 也可切换聚焦视图。",
    ),
    ("Expected Y or RGB EXR channels.", "EXR 必须使用 Y 或 RGB 通道。"),
    ("Expected a grayscale or RGB PNG8/16.", "需要灰度或 RGB 的 8/16 位 PNG。"),
    ("Expected a grayscale or RGB array.", "需要灰度或 RGB 数组。"),
    ("Expected a single-part scanline OpenEXR.", "需要单部分、扫描线格式的 OpenEXR。"),
    (
        "Expected canonical left, right, coverage image data.",
        "需要按左侧、右侧、覆盖范围排列的标准图像数据。",
    ),
    ("Expected finite float32 EXR samples.", "EXR 样本必须为有限的 float32 数值。"),
    ("Expected full-resolution FLOAT EXR channels.", "EXR 通道必须为全分辨率 FLOAT 类型。"),
    ("Expected two finite head-space threshold fields.", "需要两个数值有限的头部空间阈值场。"),
    ("Expected uint8 or uint16 PNG samples.", "PNG 样本必须为 uint8 或 uint16 类型。"),
    ("Expected uncompressed increasing-Y EXR.", "需要未压缩且按 Y 递增排列的 EXR。"),
    (
        "Export the configured SDF textures and editable project, then close the editor.",
        "导出配置好的 SDF 纹理和可编辑工程，然后关闭编辑器。",
    ),
    ("Face coverage", "面部覆盖范围"),
    ("Face forward and up must be different directions.", "面部朝前方向和朝上方向不能相同。"),
    ("Face vertex group", "面部顶点组"),
    ("Faces: {count}", "面数：{count}"),
    ("Fewer keyframes", "减少关键帧"),
    ("File name", "文件名"),
    ("Files to generate", "将生成的文件"),
    (
        "Fill this curve with shadow on the current keyframe. Later Lit cutouts still protect earlier keyframes.",
        "在当前关键帧将曲线内部填为阴影。后续关键帧的亮部仍会保留在更早关键帧中。",
    ),
    ("Finish or close the current SDF authoring session first.", "请先完成或关闭当前 SDF 编辑。"),
    (
        "Finish or close the current authoring session before opening another project.",
        "打开其他工程前，请先完成或关闭当前编辑。",
    ),
    (
        "Fit the preset to the markers and open the first Left → Right keyframe.",
        "按标记拟合预设，并打开“左 → 右”的第一个关键帧。",
    ),
    ("Fitting markers", "拟合标记"),
    ("Flat mask", "平面遮罩"),
    ("Focus", "聚焦"),
    ("Focus view", "聚焦视图"),
    ("Frame face", "居中面部"),
    ("Free", "自由"),
    ("Free handles", "自由控制柄"),
    ("Front", "正面"),
    ("Front view", "前视图"),
    ("Frontal surface only", "仅正面表面"),
    ("Full floating-point precision; larger files", "完整浮点精度；文件较大"),
    ("Generate & Finish", "生成并完成"),
    ("Generate & finish", "生成并完成"),
    ("Generation cancelled; authoring data retained.", "已取消生成，编辑数据已保留。"),
    ("Generation is already running or this session is closed.", "正在生成，或本次编辑已关闭。"),
    (
        "Give selected points independently adjustable incoming and outgoing Bézier handles.",
        "为所选点启用可独立调整的入、出贝塞尔控制柄。",
    ),
    ("Gray", "灰度"),
    ("Handles", "控制柄"),
    ("Hide", "隐藏"),
    (
        "Hide this curve’s effect, including carried light.",
        "隐藏此曲线的效果，包括应用到更早关键帧的亮部。",
    ),
    (
        "Hide this message. The artwork still needs to pass validation before export.",
        "隐藏此消息。导出前，曲线仍需通过验证。",
    ),
    ("Incoming offset", "入控制柄偏移"),
    ("Incomplete or invalid PNG end.", "PNG 结束数据不完整或无效。"),
    ("Insert", "插入"),
    (
        "Insert a keyframe in this sweep by copying nearby artwork. Mirroring also updates the opposite row.",
        "复制相邻形状，在当前扫掠中插入关键帧。启用镜像时也会更新另一行。",
    ),
    ("Insert point", "插入控制点"),
    ("Invalid EXR attribute.", "EXR 属性无效。"),
    ("Invalid EXR channel list.", "EXR 通道列表无效。"),
    ("Invalid EXR image size.", "EXR 图像尺寸无效。"),
    ("Invalid EXR pixel data.", "EXR 像素数据无效。"),
    ("Invalid EXR scanline offset.", "EXR 扫描线偏移无效。"),
    ("Invalid EXR scanline.", "EXR 扫描线无效。"),
    ("Invalid EXR string.", "EXR 字符串无效。"),
    ("Invalid EXR windows.", "EXR 数据窗口无效。"),
    ("Invalid PNG header.", "PNG 文件头无效。"),
    ("Invalid PNG signature.", "PNG 文件标识无效。"),
    ("Invalid authoring stage.", "编辑步骤无效。"),
    ("Invalid contour operation or point count.", "轮廓运算或控制点数量无效。"),
    ("Invalid handle mode.", "控制柄模式无效。"),
    ("Invalid landmark anchor.", "标记锚点无效。"),
    ("Invalid landmark barycentric coordinates.", "标记重心坐标无效。"),
    ("Invalid landmark position.", "标记位置无效。"),
    ("Invalid landmark surface reference.", "标记表面引用无效。"),
    ("Invalid point or handle coordinates.", "控制点或控制柄坐标无效。"),
    ("Invalid reference appearance.", "参考显示方式无效。"),
    ("Invalid shadow keyframe count.", "阴影关键帧数量无效。"),
    ("Keep the first and last keyframes of each sweep.", "请保留每次扫掠的首尾关键帧。"),
    (
        "Keep the main boundary endpoints and at least three points in a closed curve.",
        "请保留主边界端点；闭合曲线至少保留三个点。",
    ),
    (
        "Keep the main boundary endpoints; move them instead.",
        "主边界端点必须保留，请移动端点来调整。",
    ),
    (
        "Keyframe positions must increase from 0 to 1 within each sweep.",
        "每次扫掠中的关键帧位置必须从 0 到 1 递增。",
    ),
    ("Keyframes per sweep", "每次扫掠关键帧数"),
    ("Left shadow", "左侧阴影"),
    ("Left → Right", "左 → 右"),
    ("Light rotation · {rotation:.0f}°", "光照旋转 · {rotation:.0f}°"),
    ("Lit area", "亮部"),
    ("Live shadow preview", "实时阴影预览"),
    ("Main boundary", "主边界"),
    (
        "Make a mesh active before creating an SDF project.",
        "创建 SDF 工程前，请先激活一个网格对象。",
    ),
    ("Make a mesh active.", "请激活一个网格对象。"),
    ("Make sharp corners at selected points.", "将所选点设为尖角。"),
    ("Material reference", "材质参考"),
    ("Materials", "材质"),
    ("Mirror Full Sweep", "镜像完整扫掠"),
    ("Mirrored sweeps must have matching keyframe positions.", "镜像扫掠的关键帧位置必须一致。"),
    ("Missing PNG header.", "缺少 PNG 文件头。"),
    ("Missing or invalid authoring source settings.", "源模型设置缺失或无效。"),
    ("More keyframes", "增加关键帧"),
    ("More pronounced nose profile", "更明显的鼻部轮廓"),
    ("Mouth Center", "嘴部中心"),
    ("Mouth center", "嘴部中心"),
    ("Move", "移动"),
    ("Move / Rotate / Scale…", "移动 / 旋转 / 缩放…"),
    ("Move X", "移动 X"),
    ("Move Y", "移动 Y"),
    ("Move layer down", "图层下移"),
    ("Move layer up", "图层上移"),
    (
        "Move, rotate or scale the entire selected curve using numeric values.",
        "输入数值以移动、旋转或缩放整条所选曲线。",
    ),
    ("Needs attention", "需要处理"),
    ("Neutral", "中性"),
    ("Neutral reference", "中性参考"),
    ("Next Step  →", "下一步  →"),
    ("Next step", "下一步"),
    ("No face triangles were found.", "未找到面部三角形。"),
    (
        "No front-facing face surface. Reset the face orientation.",
        "没有朝前的面部表面。请重设面部朝向。",
    ),
    ("No recovery drafts are available.", "没有可恢复的草稿。"),
    ("No visible face surface for fitting markers.", "没有可用于放置拟合标记的可见面部表面。"),
    (
        "No visible front-facing face texels. Check the forward/up alignment and face region.",
        "没有可见的正面纹素。请检查朝前、朝上方向及面部区域。",
    ),
    ("Nose", "鼻子"),
    ("Nose Accent", "鼻部强化"),
    ("Number of keyframes in each complete boundary sweep", "每次完整边界扫掠的关键帧数量"),
    ("Off", "关闭"),
    ("Only closed shapes can be duplicated.", "只能复制闭合形状。"),
    (
        "Open an editable SDF project and validate its source model",
        "打开可编辑 SDF 工程并验证源模型",
    ),
    ("Orient the face to front view.", "将面部调整为正视图。"),
    ("Outgoing offset", "出控制柄偏移"),
    ("Output UV map", "输出 UV 贴图"),
    ("Output file stem", "输出基础文件名"),
    ("Output packing", "输出通道打包"),
    ("Output precision", "输出精度"),
    (
        "Overlapping face UV triangles {first} and {second}. Choose a unique face UV map; shadow symmetry does not resolve shared texels.",
        "面部 UV 三角形 {first} 和 {second} 重叠。请选择无重叠的面部 UV 贴图；阴影对称无法解决纹素共享。",
    ),
    ("PNG CRC verification failed.", "PNG CRC 校验失败。"),
    (
        "Pack this map into the {channel} channel. If occupied, the two map assignments swap.",
        "将此纹理打包到 {channel} 通道。如果通道已占用，两张纹理将交换通道。",
    ),
    ("Pause", "暂停"),
    ("Pause rotation", "暂停旋转"),
    ("Pause the light orbit.", "暂停光照旋转。"),
    (
        "Place Nose above Mouth Center, and Mouth Center above Chin.",
        "鼻子标记应在嘴部中心上方，嘴部中心应在下巴上方。",
    ),
    (
        "Place Nose, Mouth Center, and Chin on the face before fitting.",
        "拟合前，请将鼻子、嘴部中心和下巴标记放到面部对应位置。",
    ),
    ("Place markers.", "放置标记。"),
    ("Play 360°", "播放 360°"),
    ("Point (head space)", "控制点（头部空间）"),
    ("Point coordinates", "控制点坐标"),
    ("Point {index}", "控制点 {index}"),
    ("Preview appearance", "预览外观"),
    (
        "Preview copies of the source materials under studio lighting.",
        "在工作室光照下预览源材质的副本。",
    ),
    ("Previous step", "上一步"),
    ("Project file exceeds the 16 MB limit.", "工程文件超过 16 MB 限制。"),
    ("Project is missing {key}.", "工程缺少 {key}。"),
    ("Project round-trip verification failed.", "工程写入后重新读取验证失败。"),
    ("Projection coverage", "投影覆盖范围"),
    ("Recover Latest Draft", "恢复最新草稿"),
    ("Recovery draft unavailable: {details}", "无法使用恢复草稿：{details}"),
    ("Redo", "重做"),
    ("Reference & view", "参考与视图"),
    (
        "Reflect this entire sweep into the opposite row, keeping keyframe order. This replaces the opposite row’s artwork.",
        "将当前完整扫掠镜像到另一行，保持关键帧顺序。这会替换另一行的形状。",
    ),
    ("Relink to Active Source", "重新关联活动源模型"),
    ("Remove", "移除"),
    ("Remove keyframe", "移除关键帧"),
    ("Remove point", "移除控制点"),
    ("Remove the selected closed curve from this keyframe.", "从当前关键帧中移除所选闭合曲线。"),
    (
        "Remove this keyframe from its sweep. The first and last keyframes are retained.",
        "从当前扫掠中移除此关键帧。首尾关键帧会保留。",
    ),
    ("Reopen the most recent automatic recovery draft", "重新打开最新的自动恢复草稿"),
    ("Replace & Generate", "替换并生成"),
    ("Replace existing SDF output?", "替换已有 SDF 输出？"),
    (
        "Replace this keyframe’s artwork with the preceding keyframe in this row.",
        "用此行的上一关键帧形状替换当前形状。",
    ),
    ("Resolution", "分辨率"),
    ("Restore the curve and preview views side by side.", "恢复曲线视图与预览视图的并排布局。"),
    ("Restore the last undone edit. Ctrl+Shift+Z.", "恢复上一次撤销的编辑。Ctrl+Shift+Z。"),
    ("Return to face orientation.", "返回面部定向步骤。"),
    ("Return to markers without losing their positions.", "返回标记步骤，保留标记位置。"),
    (
        "Return to the first Left → Right keyframe. Your curves are kept.",
        "返回“左 → 右”的第一个关键帧。曲线会保留。",
    ),
    (
        "Review the captured facial surface and output UV map. Return to orientation to change the UV map.",
        "查看已选面部表面和输出 UV 贴图。需返回定向步骤才能更换 UV 贴图。",
    ),
    (
        "Review the complete 360° light rotation and choose where to save.",
        "检查完整的 360° 光照旋转，并选择保存位置。",
    ),
    ("Right", "右侧"),
    ("Right shadow", "右侧阴影"),
    ("Right view", "右视图"),
    ("Right → Left", "右 → 左"),
    ("Rotate", "旋转"),
    ("Rotate (degrees)", "旋转（度）"),
    (
        "Rotate through Front, character left, Back, character right and Front. The opposite map is sampled backward on the return half.",
        "光照依次经过正面、角色左侧、背面、角色右侧，再回到正面。后半圈反向采样另一张纹理。",
    ),
    ("Save & close", "保存并关闭"),
    ("Save Draft & Close", "保存草稿并关闭"),
    ("Save draft & close", "保存草稿并关闭"),
    ("Save location", "保存位置"),
    (
        "Save the editable project without a texture, then restore the original workspace.",
        "保存可编辑工程（不生成纹理），然后恢复原工作区。",
    ),
    (
        "Save this map as its own single-channel image using the selected output precision.",
        "以所选输出精度，将此纹理单独保存为单通道图像。",
    ),
    ("Saved: {path}", "已保存：{path}"),
    ("Scale", "缩放"),
    ("Select Fitting Landmark", "选择拟合标记"),
    ("Select Shadow Keyframe", "选择阴影关键帧"),
    ("Select Shape", "选择形状"),
    ("Select a closed curve first.", "请先选择一条闭合曲线。"),
    ("Select a source mesh first.", "请先选择源网格。"),
    (
        "Select all points of this curve. Move/Rotate/Scale shortcuts adjust them together.",
        "选择此曲线的所有控制点。可用移动、旋转、缩放快捷键一起调整。",
    ),
    ("Select curve points first.", "请先选择曲线控制点。"),
    (
        "Select facial geometry in Edit Mode, or choose Vertex Group.",
        "请在编辑模式下选择面部几何，或选择“顶点组”。",
    ),
    (
        "Select facial geometry in Edit Mode, then Create.",
        "在编辑模式下选择面部几何，然后点击“创建”。",
    ),
    (
        "Select this marker, then drag it onto the matching feature on the face.",
        "选择此标记，再将其拖到面部对应位置。",
    ),
    ("Selected Faces", "选中的面"),
    ("Separate", "单独保存"),
    (
        "Set the base name shared by the textures and editable project.",
        "设置纹理和可编辑工程共用的基础文件名。",
    ),
    (
        "Set the number of keyframes per complete sweep. Odd and even counts are supported.",
        "设置每次完整扫掠的关键帧数量，支持奇数和偶数。",
    ),
    ("Shaded preview", "着色预览"),
    ("Shadow area", "暗部"),
    ("Shadow keyframes", "阴影关键帧"),
    ("Shadow keyframes · {count}", "阴影关键帧 · {count}"),
    ("Shape transforms apply to closed shapes.", "形状变换仅适用于闭合形状。"),
    ("Show", "显示"),
    ("Show the facial features with neutral studio shading.", "使用中性的工作室着色显示面部特征。"),
    (
        "Show this curve’s effect, including carried light.",
        "显示此曲线的效果，包括应用到更早关键帧的亮部。",
    ),
    ("Smaller files with coarser transitions", "文件较小，阈值精度较低"),
    ("Smooth", "平滑"),
    ("Smooth handles", "平滑控制柄"),
    (
        "Smooth selected points using automatically aligned Bézier handles.",
        "使用自动对齐的贝塞尔控制柄平滑所选点。",
    ),
    ("Smooth shadow thresholds", "平滑阴影阈值"),
    (
        "Smooth threshold values before UV baking. Can alter small details; does not soften hard-cutoff shadows. 0 is Off; sigma is scaled from a 2048-pixel face canvas.",
        "在 UV 烘焙前平滑阈值。可能改变细节，但不会软化硬截断阴影。0 表示关闭；sigma 以 2048 像素面部画布为基准缩放。",
    ),
    ("Smoothing", "平滑强度"),
    ("Smoothing must be a finite number from 0 to 8.", "平滑强度必须为 0 到 8 之间的有限数。"),
    ("Smoothing value", "平滑数值"),
    ("Source", "来源"),
    ("Source / UV…", "源模型 / UV…"),
    ("Source and UV", "源模型与 UV"),
    ("Source: {name}", "源模型：{name}"),
    (
        "Split the following segment while preserving the current curve.",
        "细分下一段曲线，同时保持当前形状。",
    ),
    ("Split views", "并排视图"),
    (
        "Start with a more pronounced nose profile fitted to the markers.",
        "按标记拟合预设，使用更明显的鼻部轮廓。",
    ),
    (
        "Start with straight shadow boundaries and editable points at the marker heights.",
        "使用直线阴影边界，并在标记高度处设置可编辑控制点。",
    ),
    ("Starting preset", "初始预设"),
    ("Stop generation and keep the current editing session.", "停止生成，保留当前编辑会话。"),
    ("Straight boundaries across the entire face", "整张面部使用直线边界"),
    ("Switch to shaded preview.", "切换到着色预览。"),
    ("Switch to the flat black-and-white mask.", "切换到平面的黑白遮罩。"),
    ("Texture Map Output", "纹理输出"),
    ("Texture contains non-finite values.", "纹理中含有非有限数值。"),
    ("Texture maps must use R, G, B, or Separate.", "纹理必须使用 R、G、B 通道或“单独保存”。"),
    ("Texture resolution", "纹理分辨率"),
    (
        "That point is outside supported frontal coverage. Choose a visible facial surface.",
        "该点不在支持的正面覆盖范围内。请选择可见的面部表面。",
    ),
    (
        "The SDF recovery directory could not be created in Blender user data.",
        "无法在 Blender 用户数据中创建 SDF 恢复目录。",
    ),
    ("The distance transform requires a 2D mask.", "距离变换需要二维遮罩。"),
    (
        "The edit could not be completed. You can continue editing.",
        "无法完成此次编辑。你可以继续操作。",
    ),
    ("The evaluated mesh has lost the selected UV map.", "求值后的网格丢失了所选 UV 贴图。"),
    ("The face has no finite UV triangles.", "面部没有数值有效的 UV 三角形。"),
    (
        "The face projection has zero width or height. Orbit to face the character.",
        "面部投影的宽度或高度为零。请旋转视图，使其朝向角色。",
    ),
    (
        "The face region is empty. Select complete visible faces or a group containing complete faces.",
        "面部区域为空。请选择完整的可见面，或包含完整面的顶点组。",
    ),
    ("The first and last keyframes of this sweep must be kept.", "必须保留此次扫掠的首尾关键帧。"),
    ("The first keyframe has no preceding keyframe.", "第一个关键帧没有上一关键帧。"),
    ("The first keyframe has no previous keyframe.", "第一个关键帧没有上一关键帧。"),
    ("The floating editor could not initialize.", "无法初始化浮动编辑器。"),
    ("The frontal subset is empty. Reset the face orientation.", "正面区域为空。请重设面部朝向。"),
    ("The image is empty.", "图像为空。"),
    ("The main boundary cannot be deleted.", "不能删除主边界。"),
    ("The main boundary stays first.", "主边界必须位于首层。"),
    ("The maximum is 33 keyframes per sweep.", "每次扫掠最多可有 33 个关键帧。"),
    ("The project requires two complete boundary sweeps.", "工程需要两次完整的边界扫掠。"),
    (
        "The saved face region no longer matches the mesh. Relink the source.",
        "保存的面部区域与网格不再匹配。请重新关联源模型。",
    ),
    ("The saved image failed numeric verification.", "保存的图像未通过数值验证。"),
    ("The selected region contains degenerate mesh triangles.", "所选区域包含退化的网格三角形。"),
    (
        "The source geometry, pose, or UVs changed. Reopen with 'Relink to Active Source' after checking its face region.",
        "源模型的几何、姿态或 UV 已更改。检查面部区域后，请启用“重新关联活动源模型”再次打开。",
    ),
    ("The source has no UV map named {uv_name}.", "源模型没有名为 {uv_name} 的 UV 贴图。"),
    ("There are no edits to redo.", "没有可重做的编辑。"),
    ("There are no edits to undo.", "没有可撤销的编辑。"),
    ("This action is unavailable in the current state.", "当前状态下无法执行此操作。"),
    ("This action is unavailable in the current step.", "当前步骤中无法执行此操作。"),
    ("This contour needs its remaining points.", "此轮廓需要保留剩余控制点。"),
    ("This curve is already the first editable layer.", "此曲线已位于第一个可编辑图层。"),
    ("This curve is already the last layer.", "此曲线已位于最后一层。"),
    ("This is the first step.", "当前已是第一步。"),
    ("This session is closed or generation is running.", "本次编辑已关闭，或正在生成。"),
    (
        "This version needs topology-preserving evaluation. Disable topology-changing modifiers on a source copy before authoring.",
        "当前版本要求求值过程保留拓扑。编辑前，请在源模型副本上禁用会改变拓扑的修改器。",
    ),
    ("Too many PNG rows.", "PNG 行数过多。"),
    ("Too many shapes in a keyframe.", "一个关键帧中的形状过多。"),
    ("Top", "顶部"),
    ("Top view", "顶视图"),
    ("Transfer to UV map", "转移到 UV 贴图"),
    ("Transform Closed Shape", "变换闭合形状"),
    ("Transform curve", "变换曲线"),
    ("Triangle", "三角形"),
    ("Truncated EXR scanline.", "EXR 扫描线数据不完整。"),
    ("Truncated PNG chunk.", "PNG 数据块不完整。"),
    ("UV island padding", "扩展 UV 岛边缘"),
    ("Undo", "撤销"),
    ("Undo the last authoring edit. Ctrl+Z.", "撤销上一次编辑。Ctrl+Z。"),
    ("Unexpected EXR trailing data.", "EXR 末尾存在意外数据。"),
    ("Unexpected chunk in numerical PNG.", "数值 PNG 中存在意外数据块。"),
    ("Unknown authoring action.", "未知的编辑操作。"),
    ("Unknown face region type.", "未知的面部区域类型。"),
    ("Unknown texture map or output channel.", "未知纹理或输出通道。"),
    (
        "Unlink the two complete sweeps for independent artwork and keyframe counts.",
        "取消两次完整扫掠的关联，使形状和关键帧数量可以独立编辑。",
    ),
    ("Unsupported output bit depth.", "不支持此输出位深。"),
    (
        "Unsupported project format. Create a new Anime SDF Gen project with this release.",
        "不支持此工程格式。请使用当前版本创建新的 Anime SDF Gen 工程。",
    ),
    ("Unsupported texture encoding convention.", "不支持此纹理编码约定。"),
    ("Unsupported texture resolution.", "不支持此纹理分辨率。"),
    ("Up", "上移"),
    ("Use Blender’s exact front view. Numpad 1.", "切换到 Blender 的精确前视图。小键盘 1。"),
    ("Use Blender’s exact right view. Numpad 3.", "切换到 Blender 的精确右视图。小键盘 3。"),
    ("Use Blender’s exact top view. Numpad 7.", "切换到 Blender 的精确顶视图。小键盘 7。"),
    ("Use one fewer keyframe per sweep when fitting.", "拟合时，每次扫掠减少一个关键帧。"),
    ("Use one more keyframe per sweep when fitting.", "拟合时，每次扫掠增加一个关键帧。"),
    (
        "Use polygons whose vertices all have positive weight in a group",
        "使用所有顶点在指定顶点组中均具有正权重的多边形",
    ),
    ("Use this authoring control.", "使用此编辑控件。"),
    (
        "Use this view as the face’s front and place default markers.",
        "将当前视图设为面部正面，并放置默认标记。",
    ),
    (
        "Use visible selected polygons on the active Edit Mode mesh",
        "使用活动网格在编辑模式下选中的可见多边形",
    ),
    (
        "V1 requires the selected face UVs inside a single 0–1 tile.",
        "当前版本要求所选面部 UV 位于单个 0–1 区域内。",
    ),
    (
        "Validate the face and open an isolated curve-authoring preview",
        "验证面部，并打开独立的曲线编辑预览",
    ),
    (
        "Verification reader expects the author's unfiltered PNG rows.",
        "验证读取器需要本工具写入的未过滤 PNG 行数据。",
    ),
    ("Verified {filename}", "已验证 {filename}"),
    ("Verify and commit output files", "验证并写入输出文件"),
    (
        "Verify and export the textures and editable project, then restore your workspace",
        "验证并导出纹理和可编辑工程，然后恢复工作区",
    ),
    ("Verify {filename}", "验证 {filename}"),
    ("Vertex Group", "顶点组"),
    (
        "Vertex group '{group}' is missing on {object_name}.",
        "{object_name} 上缺少顶点组“{group}”。",
    ),
    (
        "Vertex-group membership changed. Relink the source before regenerating.",
        "顶点组成员已更改。重新生成前，请重新关联源模型。",
    ),
    ("Wait for generation to finish or cancel it.", "请等待生成完成，或取消生成。"),
    ("Wait for the authoring view to open.", "请等待编辑视图打开。"),
    (
        "Your authoring session is in the Anime SDF Gen popup.",
        "当前编辑位于 Anime SDF Gen 浮动窗口中。",
    ),
    (
        "{count} face triangles have zero-area UVs (first triangle {triangle}).",
        "{count} 个面部三角形的 UV 面积为零（首个三角形为 {triangle}）。",
    ),
    ("{direction} keyframe {index}/{count}", "{direction}关键帧 {index}/{count}"),
    ("{direction} · Keyframe {index}", "{direction} · 关键帧 {index}"),
    ("{label} · {progress:.0%}", "{label} · {progress:.0%}"),
    ("{name} copy", "{name} 副本"),
    ("{name} marker", "{name}标记"),
    ("{name} {number}", "{name} {number}"),
    ("{name} · {channel}", "{name} · {channel}"),
    (
        "{name}: contour crosses itself or has coincident points.",
        "{name}：轮廓自相交或存在重合点。",
    ),
    ("{name}: {count} pixels", "{name}：{count} 个像素"),
    (
        "{path}\nChoose the folder and file name. Files are written by Generate & Finish.",
        "{path}\n选择文件夹和文件名。点击“生成并完成”后写入文件。",
    ),
    (
        "{direction} keyframes {before} → {after}: {count} pixels become lit again outside carried cutouts. Adjust the main boundary or shadow shapes.",
        "{direction}关键帧 {before} → {after}：继承亮部以外有 {count} 个像素重新变亮。请调整主边界或阴影形状。",
    ),
)
